version: "3"

services:
  mariadb:
    image: mariadb:10.3
    ports:
      - '3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: db
      MYSQL_PASSWORD: db
      MYSQL_DATABASE: db

  phpfpm:
    image: itkdev/php7.0-fpm:latest
    # environment:
    #   PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
    restart: always
    depends_on:
      - mariadb
    volumes:
      - .:/app:delegated

  nginx:
    image: nginx:latest
    depends_on:
      - phpfpm
    ports:
      - '80'
    volumes:
      - ${PWD}/.docker/vhost.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:/app:delegated
    labels:
      - "traefik.frontend.rule=Host:dokk1gh.docker.localhost"

  reverse-proxy:
    image: traefik  # The official Traefik docker image
    command: --api --docker  # Enables the web UI and tells Traefik to listen to docker
    ports:
      - "80"
      - "8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # So that Traefik can listen to the Docker events

  mailhog:
    image: mailhog/mailhog
