imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: easy_admin.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        # save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
        # If running inside a Vagrant box, use this:
        save_path: /var/lib/php/sessions
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        site_name: '%site_name%'
        site_url: '%site_url%'
        header_image_url: "%header_image_url%"
        password_resetting:
            subject: '%password_resetting_subject%'
            header: '%password_resetting_header%'
            body: '%password_resetting_body%'
            button:
                text: '%password_resetting_button_text%'
            footer: '%password_resetting_footer%'
        sender:
            email: '%mailer_email%'
            name: '%mailer_name%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.project_dir%/var/data/data.sqlite"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        filters:
            softdeleteable:
                class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                enabled: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    port: '%mailer_port%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: AppBundle\Entity\User
    from_email:
        address: "%mailer_email%"
        sender_name: "%mailer_name%"
    service:
        user_manager: AppBundle\Service\UserManager
        mailer: fos_user.mailer.twig_swift
    resetting:
        email:
            template: Emails/password_resetting.email.twig
    resetting:
        token_ttl: 0

fos_rest:
    param_fetcher_listener: true
    body_listener: true
    format_listener:
        enabled: true
        rules:
            - { path: '^/api/', priorities: ['json', 'xml'], fallback_format: 'json', prefer_extension: true }
    versioning: true
    view:
        formats:
            xml:  true
            json: true
        view_response_listener: 'force'
    zone:
        - { path: ^/api/* }

nelmio_api_doc:
    documentation:
        info:
            title: "%api_title%"
            description: "%api_description%"
            version: 1.0.0
    routes:
        path_patterns: # an array of regexps
            - ^/api

stof_doctrine_extensions:
    orm:
        default:
            timestampable: true
            blameable: true
            softdeleteable: true
