imports:
    - { resource: config_test.yml }

parameters:
    format_datetime: 'Y-m-d H:i'
    format_date: 'Y-m-d'
    format_time: 'H:i'
    locale: da
    aoes_location: 'http://dokk1gh.vm/mock/aeosws'

framework:
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

doctrine:
    dbal:
        dbname: "%database_name%_acceptance"
