easy_admin:
    site_name: '%site_name%'

    entities:
        Code:
            class: AppBundle\Entity\Code
            form:
                fields:
                    - property: startTime
                    - property: endTime
                    - property: template

        User:
            class: AppBundle\Entity\User
            list:
                fields:
                    - property: email
                    - property: roles
                    - property: templates
                      template: templates.html.twig
                    - property: enabled
                      type: boolean
                    - property: last_login
                      type: datetime
            new:
                fields:
                    - property: enabled
                    # - property: username
                    - property: email
                      type: email
                    - property: plainPassword
                      type: text
                      type_options:
                          required: true
                    - property: roles
                      type: choice
                      type_options:
                          multiple: true
                          expanded: true
                          choices: &role_list
                              ROLE_USER: ROLE_USER
                              ROLE_ADMIN: ROLE_ADMIN
                    - property: templates
            edit:
                fields:
                    - property: enabled
                    # - property: username
                    - property: email
                      type: email
                    - property: roles
                      type: choice
                      type_options:
                          multiple: true
                          expanded: true
                          choices:
                              <<: *role_list
                    - property: templates
                    - property: plainPassword
                      help: app.user.help.plainPassword
                      type: text
                      type_options:
                          required: false

        Template:
            class: AppBundle\Entity\Template
