easy_admin:
    site_name: '%site_name%'

    design:
        form_theme: 'easy_admin/form/bootstrap_3_horizontal_layout.html.twig'
        brand_color: '#003764'
        assets:
            css:
                - 'stylesheets/easy_admin/easy_admin.css'

        menu:
            - entity: Code
              icon: id-card
            - entity: Guest
              icon: id-card
            - entity: User
              icon: user
              roles: [ROLE_ADMIN]
            - entity: Template
              roles: [ROLE_ADMIN]

    formats:
        datetime: '%format_datetime%'

    entities:
        Code:
            controller: AppBundle\Controller\CodeController
            class: AppBundle\Entity\Code
            disabled_actions: [show, edit]
            list:
                actions: [-show]
                fields:
                    - property: identifier
                      label: Code
                      template: code.html.twig
                    - property: status
                      sortable: true
                      template: status.html.twig
                    - property: startTime
                      label: Time range
                      template: date_time_range.html.twig
                    - property: template
                    - property: note
                      sortable: false
                      template: note.html.twig
                    - property: createdAt
                      template: datetime.html.twig
                    - property: createdBy
                      roles: [ROLE_ADMIN]
            show:
                fields:
                    - property: startTime
                    - property: endTime
                    - property: template
                    - property: identifier

            form:
                fields:
                    - property: startTime
                      label: Date
                      type_options:
                          view_timezone: "%view_timezone%"
                          required: true
                          widget: single_text
                          html5: false
                    - property: endTime
                      label: Period
                      type_options:
                          view_timezone: "%view_timezone%"
                          required: true
                          widget: single_text
                          html5: false
                    - property: template
                    - property: note
                      help: code.note.help

        Guest:
            controller: AppBundle\Controller\GuestController
            roles: [ROLE_ADMIN]
            class: AppBundle\Entity\Guest
            disabled_actions: [show, delete]
            list:
                actions: [showApp]
                fields:
                    - property: name
                    - property: company
                    - property: enabled
                      type: boolean
                    - property: activatedAt
                    - property: phone
                    - property: email
                    - property: templates
                      template: templates.html.twig
                    - property: startTime
                    - property: endTime
                    - property: createdAt
                      template: datetime.html.twig
                    - property: createdBy
                      roles: [ROLE_ADMIN]

            new:
                fields:
                    - property: name
                    - property: company
                    - property: phone
                    - property: email
                      type: email
                    - property: templates
                      type_options:
                          expanded: true
                          required: true
                    - property: startTime
                      label: Start date
                      type: date
                    - property: endTime
                      label: End date
                      type: date
                    - property: timeRanges
                      type: AppBundle\Form\TimeRangesType

            edit:
                fields:
                    - property: enabled
                    - property: name
                    - property: company
                    - property: phone
                    - property: email
                      type: email
                    - property: templates
                      type_options:
                          expanded: true
                          required: true
                    - property: startTime
                      label: Start date
                      type: date
                    - property: endTime
                      label: End date
                      type: date
                    - property: timeRanges
                      type: AppBundle\Form\TimeRangesType

        User:
            controller: AppBundle\Controller\UserController
            roles: [ROLE_ADMIN]
            class: AppBundle\Entity\User
            disabled_actions: [show, delete]
            list:
                fields:
                    - property: email
                    - property: enabled
                      type: boolean
                    - property: aeosId
                    - property: roles
                      template: roles.html.twig
                      sortable: false
                    - property: templates
                      template: templates.html.twig
                    - property: lastLogin
                    - property: createdAt
                      template: datetime.html.twig
                    - property: createdBy
                    - property: updatedAt
                      template: datetime.html.twig
                    - property: updatedBy
            new:
                fields:
                    - property: email
                      type: email
                    - property: roles
                      type: choice
                      type_options:
                          multiple: true
                          expanded: true
                          choices: &role_list
                              ROLE_USER: ROLE_USER
                              ROLE_ADMIN: ROLE_ADMIN
                    - property: templates
                      type_options:
                          expanded: true
                          required: true
                    - property: aeosId
            edit:
                fields:
                    - property: enabled
                    - property: email
                      type: email
                    - property: roles
                      type: choice
                      type_options:
                          multiple: true
                          expanded: true
                          choices:
                              <<: *role_list
                    - property: templates
                      type_options:
                          expanded: true
                          required: true
                    - property: aeosId

        Template:
            roles: [ROLE_ADMIN]
            class: AppBundle\Entity\Template
            disabled_actions: [show, delete]
            list:
                fields:
                    - property: name
                    - property: enabled
                      type: boolean
                    - property: aeosId
                    - property: createdAt
                      template: datetime.html.twig
                    - property: createdBy
                    - property: updatedAt
                      template: datetime.html.twig
                    - property: updatedBy
            form:
                fields:
                    - property: enabled
                    - property: name
                    - property: aeosId
                      type_options:
                          required: false
