easy_admin:
    site_name: '%site_name%'

    design:
        menu:
            - entity: Code
            - entity: User
              roles: [ROLE_ADMIN]
            - entity: Template
              roles: [ROLE_ADMIN]

    entities:
        Code:
            class: AppBundle\Entity\Code
            list:
                actions: [show]
                fields:
                    - property: startTime
                    - property: endTime
                    - property: template
                    - property: createdAt
                    - property: createdBy
                      roles: [ROLE_ADMIN]
                    - property: updatedAt
                    - property: updatedBy
                      roles: [ROLE_ADMIN]
            show:
                fields:
                    - property: startTime
                    - property: endTime
                    - property: template
                    - property: identifier

            form:
                fields:
                    - property: startTime
                    - property: endTime
                    - property: template

        User:
            roles: [ROLE_ADMIN]
            class: AppBundle\Entity\User
            list:
                fields:
                    - property: email
                    - property: aeosId
                    - property: roles
                    - property: templates
                      template: templates.html.twig
                    - property: enabled
                      type: boolean
                    - property: last_login
                      type: datetime
                    - property: createdAt
                    - property: createdBy
                    - property: updatedAt
                    - property: updatedBy
            new:
                fields:
                    - property: enabled
                    # - property: username
                    - property: email
                      type: email
                    - property: plainPassword
                      type: text
                      type_options:
                          required: true
                    - property: roles
                      type: choice
                      type_options:
                          multiple: true
                          expanded: true
                          choices: &role_list
                              ROLE_USER: ROLE_USER
                              ROLE_ADMIN: ROLE_ADMIN
                    - property: templates
                    - property: aeosId
            edit:
                fields:
                    - property: enabled
                    # - property: username
                    - property: email
                      type: email
                    - property: roles
                      type: choice
                      type_options:
                          multiple: true
                          expanded: true
                          choices:
                              <<: *role_list
                    - property: templates
                    - property: plainPassword
                      help: app.user.help.plainPassword
                      type: text
                      type_options:
                          required: false
                    - property: aeosId

        Template:
            roles: [ROLE_ADMIN]
            class: AppBundle\Entity\Template
            list:
                fields:
                    - property: name
                    - property: aeosId
                    - property: createdAt
                    - property: createdBy
                    - property: updatedAt
                    - property: updatedBy
            form:
                fields:
                    - property: name
                    - property: aeosId
