easy_admin:
    site_name: '%site_name%'

    design:
        form_theme: 'easy_admin/form/bootstrap_3_horizontal_layout.html.twig'
        brand_color: '#003764'
        assets:
            css:
                - 'stylesheets/app.css'

        menu:
            - entity: Code
              icon: id-card
            - entity: User
              icon: user
              roles: [ROLE_ADMIN]
            - entity: Template
              roles: [ROLE_ADMIN]

    formats:
        datetime: '%format_datetime%'

    entities:
        Code:
            controller: AppBundle\Controller\CodeController
            class: AppBundle\Entity\Code
            disabled_actions: [edit]
            list:
                actions: [-show]
                fields:
                    - property: identifier
                      label: Code
                      template: code.html.twig
                    - property: status
                      sortable: true
                      template: status.html.twig
                    - property: startTime
                    - property: endTime
                    - property: template
                    - property: note
                      sortable: false
                      template: note.html.twig
                    - property: createdAt
                    - property: createdBy
                      roles: [ROLE_ADMIN]
            show:
                fields:
                    - property: startTime
                    - property: endTime
                    - property: template
                    - property: identifier

            form:
                fields:
                    - property: startTime
                    - property: endTime
                    - property: template
                    - property: note
                      help: code.note.help

        User:
            controller: AppBundle\Controller\UserController
            roles: [ROLE_ADMIN]
            class: AppBundle\Entity\User
            list:
                fields:
                    - property: email
                    - property: aeosId
                    - property: roles
                      template: roles.html.twig
                      sortable: false
                    - property: templates
                      template: templates.html.twig
                    - property: enabled
                      type: boolean
                    - property: last_login
                      type: datetime
                    - property: createdAt
                    - property: createdBy
                    - property: updatedAt
                    - property: updatedBy
            new:
                fields:
                    - property: email
                      type: email
                    - property: roles
                      type: choice
                      type_options:
                          multiple: true
                          expanded: true
                          choices: &role_list
                              ROLE_USER: ROLE_USER
                              ROLE_ADMIN: ROLE_ADMIN
                    - property: templates
                      type_options:
                          expanded: true
                          required: true
                    - property: aeosId
                      type_options:
                          required: true
            edit:
                fields:
                    - property: enabled
                    - property: email
                      type: email
                    - property: roles
                      type: choice
                      type_options:
                          multiple: true
                          expanded: true
                          choices:
                              <<: *role_list
                    - property: templates
                      type_options:
                          expanded: true
                          required: true
                    - property: aeosId
                      type_options:
                          required: true
                    - property: apiKey
                      type: AppBundle\Form\Type\ApiKeyType
                      type_options:
                          disabled: true

        Template:
            roles: [ROLE_ADMIN]
            class: AppBundle\Entity\Template
            list:
                fields:
                    - property: name
                    - property: aeosId
                    - property: createdAt
                    - property: createdBy
                    - property: updatedAt
                    - property: updatedBy
            form:
                fields:
                    - property: name
                    - property: aeosId
